<a href="https://colab.research.google.com/github/SabanaSultana/NLP/blob/main/NLP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Text Preprocessing

---



---






In [ ]:
!pip install nltk


In [ ]:
import nltk
nltk.download('punkt')
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.


True

# **Text Cleanning**

# Word, Sentence Tokenization

In [ ]:
from nltk.tokenize import sent_tokenize, word_tokenize

corpus=""" Hii my name is Sabana.
 Wow! I am so good at NLP.
 Am I? Really? """

In [ ]:
corpus

' Hii my name is Sabana.\n Wow! I am so good at NLP. \n Am I? Really? '

In [ ]:
print(corpus)

 Hii my name is Sabana.
 Wow! I am so good at NLP. 
 Am I? Really? 


In [ ]:
sent_tokenize(corpus)

[' Hii my name is Sabana.', 'Wow!', 'I am so good at NLP.', 'Am I?', 'Really?']

In [ ]:
word_tokenize(corpus)

['Hii',
 'my',
 'name',
 'is',
 'Sabana',
 '.',
 'Wow',
 '!',
 'I',
 'am',
 'so',
 'good',
 'at',
 'NLP',
 '.',
 'Am',
 'I',
 '?',
 'Really',
 '?']

In [ ]:
print(len(word_tokenize(corpus)))

20


In [ ]:
from nltk.tokenize import TreebankWordTokenizer

tokenizer=TreebankWordTokenizer()
tokenizer.tokenize(corpus)

['Hii',
 'my',
 'name',
 'is',
 'Sabana.',
 'Wow',
 '!',
 'I',
 'am',
 'so',
 'good',
 'at',
 'NLP.',
 'Am',
 'I',
 '?',
 'Really',
 '?']

In [ ]:
# tokenizer.tokenize(বাংলা একটি মধুর ও সমৃদ্ধ ভাষা, যা আমাদের সংস্কৃতি ও ঐতিহ্যের গভীর পরিচয় বহন করে। এই ভাষায় কবিতা, গল্প, গান ও নানা সাহিত্যকর্মের মাধ্যমে মানুষের অনুভূতি সুন্দরভাবে প্রকাশ পায়। বাংলা ভাষা শুধু যোগাযোগের মাধ্যম নয়, এটি আমাদের আত্মপরিচয়েরও একটি গুরুত্বপূর্ণ অংশ। মাতৃ)

# Can work on bengali langauge, but not able to understand bengali punctuation

# Word Stemming

In [ ]:
from nltk.stem import PorterStemmer

stemmer=PorterStemmer()

words=['eat', 'eats', 'eaten', 'finally', 'final', 'congratulation', 'congo', 'congrats', 'history', 'historical']

for word in words:
  print(word, ":", stemmer.stem(word))

eat : eat
eats : eat
eaten : eaten
finally : final
final : final
congratulation : congratul
congo : congo
congrats : congrat
history : histori
historical : histor


In [ ]:
from nltk.stem import RegexpStemmer

regexp_stemmer=RegexpStemmer('ing$|e|es$|$ing|^sa')   ## $ after literal means remove suffix, $ before literal not workful, ^ for prefix, only literal represent anywhere in the text

print(regexp_stemmer.stem('eating'))
print(regexp_stemmer.stem('ingeat'))
print(regexp_stemmer.stem('ingeated'))
print(regexp_stemmer.stem('sabana'))


at
ingat
ingatd
bana


In [ ]:
from nltk.stem import SnowballStemmer
stemming=SnowballStemmer('english')
for word in words:
  print(word, ":", stemming.stem(word))




eat : eat
eats : eat
eaten : eaten
finally : final
final : final
congratulation : congratul
congo : congo
congrats : congrat
history : histori
historical : histor


In [ ]:
from nltk.stem import SnowballStemmer

# Initialize SnowballStemmer for German
german_stemmer = SnowballStemmer('german')

# List of German words to stem
german_words = ['häuser', 'mädchen', 'geliebt', 'geht', 'gegangen', 'spielen', 'gespielt']

print("Stemming German words:")
for word in german_words:
  print(f"{word} : {german_stemmer.stem(word)}")

Stemming German words:
häuser : haus
mädchen : madch
geliebt : geliebt
geht : geht
gegangen : gegang
spielen : spiel
gespielt : gespielt


# Lemmatization

In [ ]:
 import nltk
 nltk.download('wordnet')

[nltk_data] Downloading package wordnet to /root/nltk_data...


True

In [ ]:
from nltk.stem import WordNetLemmatizer

lemmatizer=WordNetLemmatizer()

print(lemmatizer.lemmatize('corpora'))
print(lemmatizer.lemmatize('better', pos='n'))
print(lemmatizer.lemmatize('going', pos='n'))
print(lemmatizer.lemmatize('going', pos='v'))

corpus
better
going
go


# Stopwords

In [ ]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [ ]:
import nltk.

In [ ]:
from nltk.corpus import stopwords
stopwords.words( 'english')

para=""" Natural Language Processing (NLP) is a fascinating field at the intersection of computer science, artificial intelligence, and linguistics. It focuses on enabling computers to understand, interpret, and generate human language in a valuable way. This technology powers many everyday applications, from virtual assistants and translation tools to spam filters and sentiment analysis systems. Developing effective NLP models requires a deep understanding of linguistic structures and statistical methods. Ultimately, NLP aims to bridge the communication gap between humans and machines, making technology more intuitive and accessible for everyone """

sentences=sent_tokenize(para)

print(type(sentences))

<class 'list'>


In [ ]:
sentences

[' Natural Language Processing (NLP) is a fascinating field at the intersection of computer science, artificial intelligence, and linguistics.',
 'It focuses on enabling computers to understand, interpret, and generate human language in a valuable way.',
 'This technology powers many everyday applications, from virtual assistants and translation tools to spam filters and sentiment analysis systems.',
 'Developing effective NLP models requires a deep understanding of linguistic structures and statistical methods.',
 'Ultimately, NLP aims to bridge the communication gap between humans and machines, making technology more intuitive and accessible for everyone']

In [ ]:
for i in range(len(sentences)):
  words=word_tokenize(sentences[i])

  words=[lemmatizer.lemmatize(word) for word in words if word not in stopwords.words('english')]
  sentences[i]=' '.join(words)

In [ ]:
for sent in sentences:
  print(sent)

Natural Language Processing ( NLP ) fascinating field intersection computer science , artificial intelligence , linguistics .
It focus enabling computer understand , interpret , generate human language valuable way .
This technology power many everyday application , virtual assistant translation tool spam filter sentiment analysis system .
Developing effective NLP model requires deep understanding linguistic structure statistical method .
Ultimately , NLP aim bridge communication gap human machine , making technology intuitive accessible everyone


# Part of Speech

In [ ]:
import nltk
nltk.download('averaged_perceptron_tagger_eng')
nltk.download('maxent_ne_chunker') # 'maxent_ne_chunker_tab' was a tab completion, the correct package is 'maxent_ne_chunker'
nltk.download('words')
sentence = "I am Sabana, I live at Kolkata"
words = sentence.split() # For better tokenization, consider nltk.word_tokenize(sentence)
tagged_words = nltk.pos_tag(words)

print("POS-tagged words:", tagged_words)
print("Named Entities:")
print(nltk.ne_chunk(tagged_words))

[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger_eng is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package maxent_ne_chunker to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package maxent_ne_chunker is already up-to-date!
[nltk_data] Downloading package words to /root/nltk_data...
[nltk_data]   Unzipping corpora/words.zip.


POS-tagged words: [('I', 'PRP'), ('am', 'VBP'), ('Sabana,', 'JJ'), ('I', 'PRP'), ('live', 'VBP'), ('at', 'IN'), ('Kolkata', 'NNP')]
Named Entities:
(S
  I/PRP
  am/VBP
  Sabana,/JJ
  I/PRP
  live/VBP
  at/IN
  (ORGANIZATION Kolkata/NNP))


# Name Entity Recognition

In [ ]:
import nltk
nltk.download('punkt') # For word tokenization
nltk.download('averaged_perceptron_tagger') # For POS tagging
nltk.download('maxent_ne_chunker') # For Named Entity Recognition
nltk.download('words') # For the words corpus used by the chunker

sentence = "Barack Obama was born in Hawaii and served as the 44th President of the United States."

# Step 1: Tokenize the sentence into words
words = nltk.word_tokenize(sentence)
print(f"Tokenized words: {words}\n")

# Step 2: Perform Part-of-Speech (POS) tagging
tagged_words = nltk.pos_tag(words)
print(f"POS-tagged words: {tagged_words}\n")

# Step 3: Perform Named Entity Recognition (NER)
named_entities = nltk.ne_chunk(tagged_words)
print("Named Entities:\n")
print(named_entities)

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger.zip.
[nltk_data] Downloading package maxent_ne_chunker to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package maxent_ne_chunker is already up-to-date!
[nltk_data] Downloading package words to /root/nltk_data...
[nltk_data]   Package words is already up-to-date!


Tokenized words: ['Barack', 'Obama', 'was', 'born', 'in', 'Hawaii', 'and', 'served', 'as', 'the', '44th', 'President', 'of', 'the', 'United', 'States', '.']

POS-tagged words: [('Barack', 'NNP'), ('Obama', 'NNP'), ('was', 'VBD'), ('born', 'VBN'), ('in', 'IN'), ('Hawaii', 'NNP'), ('and', 'CC'), ('served', 'VBD'), ('as', 'IN'), ('the', 'DT'), ('44th', 'CD'), ('President', 'NNP'), ('of', 'IN'), ('the', 'DT'), ('United', 'NNP'), ('States', 'NNPS'), ('.', '.')]

Named Entities:

(S
  (PERSON Barack/NNP)
  (PERSON Obama/NNP)
  was/VBD
  born/VBN
  in/IN
  (GPE Hawaii/NNP)
  and/CC
  served/VBD
  as/IN
  the/DT
  44th/CD
  President/NNP
  of/IN
  the/DT
  (GPE United/NNP States/NNPS)
  ./.)


As you can see, the `nltk.ne_chunk` function correctly identifies "Barack Obama" as a PERSON, "Hawaii" as a GPE (Geo-Political Entity), and "United States" as a GPE, all thanks to the preceding POS tagging.

In [ ]:
# import nltk
# nltk.download('maxent_ne_chunker_tab')

# nltk.ne_chunk(['Sabana', 'I', 'Hello', 'You'])

# print("Named Entities:")
# print(nltk.ne_chunk(tagged_words))

[nltk_data] Downloading package maxent_ne_chunker_tab to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package maxent_ne_chunker_tab is already up-to-date!


IndexError: string index out of range

# **Text to Vector Conversion**

# Bag of Words

In [1]:
import nltk
import re
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [2]:
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer

ps=PorterStemmer()

In [36]:
sentences = [
    "NLP is AMAZING!!! 😃",
    "I bought 3 apples, 2 bananas, and 1 mango.",
    "Email me at example123@gmail.com.",
    "The price of Bitcoin in 2025 was $45000.",
    "Running, runner, and ran are forms of the same word.",
    "Visit https://example.com for more info.",
    "AI & ML are the future of technology.",
    "   Extra   spaces should be removed.   ",
    "COVID-19 changed the world in 2020.",
    "Is this sentence properly tokenized?"
]

In [37]:
import re
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer

ps = PorterStemmer()
stop_words = set(stopwords.words('english'))   # ✅ Store once (fast lookup)

cleaned_sentences = []

for sent in sentences:

    # 1️⃣ Lowercase
    sent = sent.lower()

    # 2️⃣ Remove non-letters
    sent = re.sub('[^a-z]', ' ', sent)

    # 3️⃣ Tokenize
    words = sent.split()

    # print(words, '...')

    # 4️⃣ Remove stopwords + Stemming
    words = [ps.stem(word) for word in words if word not in stop_words]

    print(words)

    cleaned_sentences.append(" ".join(words))

print("\nFinal Cleaned Sentences:\n", cleaned_sentences)


['nlp', 'amaz']
['bought', 'appl', 'banana', 'mango']
['email', 'exampl', 'gmail', 'com']
['price', 'bitcoin']
['run', 'runner', 'ran', 'form', 'word']
['visit', 'http', 'exampl', 'com', 'info']
['ai', 'ml', 'futur', 'technolog']
['extra', 'space', 'remov']
['covid', 'chang', 'world']
['sentenc', 'properli', 'token']

Final Cleaned Sentences:
 ['nlp amaz', 'bought appl banana mango', 'email exampl gmail com', 'price bitcoin', 'run runner ran form word', 'visit http exampl com info', 'ai ml futur technolog', 'extra space remov', 'covid chang world', 'sentenc properli token']


In [30]:
### Now do the BOW vectorization
## Create the Bag OF Words model
from sklearn.feature_extraction.text import CountVectorizer
## for Binary BOW enable binary=True
cv=CountVectorizer(max_features=10,binary=True)

In [31]:
X=cv.fit_transform(cleaned_sentences).toarray()

In [32]:
X
X.shape

(10, 10)

In [33]:
X

array([[0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 1, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 1],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [34]:
cv.vocabulary_

{'amaz': np.int64(1),
 'bought': np.int64(5),
 'appl': np.int64(2),
 'banana': np.int64(3),
 'exampl': np.int64(9),
 'com': np.int64(7),
 'bitcoin': np.int64(4),
 'ai': np.int64(0),
 'covid': np.int64(8),
 'chang': np.int64(6)}

## N Grams

In [39]:
## Create the Bag OF Words model with ngram
from sklearn.feature_extraction.text import CountVectorizer
## for Binary BOW enable binary=True
cv=CountVectorizer(max_features=20,binary=True,ngram_range=(2,3))
X=cv.fit_transform(cleaned_sentences).toarray()
X


array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0],
       [1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [40]:
X.shape

(10, 20)

In [41]:
cv.vocabulary_

{'bought appl': np.int64(5),
 'appl banana': np.int64(2),
 'banana mango': np.int64(4),
 'bought appl banana': np.int64(6),
 'appl banana mango': np.int64(3),
 'email exampl': np.int64(11),
 'exampl gmail': np.int64(15),
 'email exampl gmail': np.int64(12),
 'exampl gmail com': np.int64(16),
 'form word': np.int64(19),
 'exampl com': np.int64(13),
 'com info': np.int64(8),
 'exampl com info': np.int64(14),
 'ai ml': np.int64(0),
 'ai ml futur': np.int64(1),
 'extra space': np.int64(17),
 'extra space remov': np.int64(18),
 'covid chang': np.int64(9),
 'chang world': np.int64(7),
 'covid chang world': np.int64(10)}

# TF IDF

In [42]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [45]:
tfidf=TfidfVectorizer(max_features=20)
X=tfidf.fit_transform(cleaned_sentences).toarray()

In [46]:
import numpy as np
np.set_printoptions(edgeitems=30, linewidth=100000,
    formatter=dict(float=lambda x: "%.3g" % x))

In [47]:
X

array([[0, 0.707, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.707],
       [0, 0, 0.5, 0.5, 0, 0.5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.5, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0.458, 0, 0.539, 0.458, 0, 0, 0, 0.539, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0.458, 0, 0, 0.458, 0, 0, 0, 0, 0.539, 0.539, 0, 0, 0],
       [0.577, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.577, 0, 0, 0, 0, 0.577, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0.707, 0, 0.707, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [51]:
tfidf=TfidfVectorizer(max_features=100,ngram_range=(2,3))
X=tfidf.fit_transform(cleaned_sentences).toarray()

In [52]:
tfidf.vocabulary_

{'nlp amaz': np.int64(26),
 'bought appl': np.int64(5),
 'appl banana': np.int64(2),
 'banana mango': np.int64(4),
 'bought appl banana': np.int64(6),
 'appl banana mango': np.int64(3),
 'email exampl': np.int64(11),
 'exampl gmail': np.int64(15),
 'gmail com': np.int64(21),
 'email exampl gmail': np.int64(12),
 'exampl gmail com': np.int64(16),
 'price bitcoin': np.int64(27),
 'run runner': np.int64(31),
 'runner ran': np.int64(33),
 'ran form': np.int64(29),
 'form word': np.int64(19),
 'run runner ran': np.int64(32),
 'runner ran form': np.int64(34),
 'ran form word': np.int64(30),
 'visit http': np.int64(38),
 'http exampl': np.int64(22),
 'exampl com': np.int64(13),
 'com info': np.int64(8),
 'visit http exampl': np.int64(39),
 'http exampl com': np.int64(23),
 'exampl com info': np.int64(14),
 'ai ml': np.int64(0),
 'ml futur': np.int64(24),
 'futur technolog': np.int64(20),
 'ai ml futur': np.int64(1),
 'ml futur technolog': np.int64(25),
 'extra space': np.int64(17),
 'space re

# Word2Vec

In [55]:
!pip install gensim
import gensim

print("Sabana")


Sabana


In [56]:
from gensim.models import Word2Vec, KeyedVectors

In [57]:
import gensim.downloader as api

wv = api.load('word2vec-google-news-300')

[==================================================] 100.0% 1662.8/1662.8MB downloaded


In [58]:
vec_king = wv['king']

In [59]:
vec_king

array([0.126, 0.0298, 0.00861, 0.14, -0.0256, -0.0361, 0.112, -0.198, 0.0513, 0.363, -0.242, -0.303, -0.178, -0.0249, -0.168, -0.17, 0.0347, 0.00522, 0.0464, 0.129, 0.137, 0.113, 0.0596, 0.137, 0.101, -0.177, -0.252, 0.0598, 0.342, -0.0311, 0.104, 0.0618, 0.125, 0.4, -0.322, 0.084, 0.0391, 0.00586, 0.0703, 0.173, 0.139, -0.231, 0.283, 0.143, 0.342, -0.0239, -0.11, 0.0332, -0.0547, 0.0153, -0.162, 0.158, -0.26, 0.0201, -0.163, 0.00136, -0.145, -0.0569, 0.043, -0.0247, 0.186, 0.447, 0.00958, 0.132, 0.0986, -0.186, -0.1, -0.134, -0.125, 0.283, 0.123, 0.0532, -0.178, 0.0859, -0.0219, 0.0205, -0.14, 0.0251, 0.139, -0.105, 0.139, 0.0889, -0.0752, -0.0214, 0.173, 0.0464, -0.266, 0.00891, 0.149, 0.0378, 0.238, -0.125, -0.218, -0.182, 0.0298, 0.0571, -0.0289, 0.0125, 0.0967, -0.231, 0.0581, 0.0669, 0.0708, -0.309, -0.215, 0.146, -0.428, -0.0094, 0.154, -0.0767, 0.289, 0.277, -0.000486, -0.137, 0.324, -0.246, -0.00304, -0.212, 0.125, 0.27, 0.204, 0.0825, -0.201, -0.16, -0.0378, -0.12, 0.115, -0.

In [60]:
wv.most_similar('happy')

[('glad', 0.7408890724182129),
 ('pleased', 0.6632170677185059),
 ('ecstatic', 0.6626912355422974),
 ('overjoyed', 0.6599286794662476),
 ('thrilled', 0.6514049172401428),
 ('satisfied', 0.6437949538230896),
 ('proud', 0.636042058467865),
 ('delighted', 0.627237856388092),
 ('disappointed', 0.6269949674606323),
 ('excited', 0.6247665286064148)]

In [61]:
wv.similarity("hockey","sports")

np.float32(0.53541523)

In [62]:
vec=wv['king']-wv['man']+wv['woman']
vec

array([0.043, -0.178, -0.129, 0.115, 0.00269, -0.102, 0.196, -0.18, 0.0195, 0.41, -0.368, -0.396, -0.157, 0.00146, -0.093, -0.116, -0.0552, -0.108, 0.0791, 0.199, 0.239, 0.0634, -0.0217, 0, 0.0472, -0.218, -0.345, 0.0637, 0.316, -0.198, 0.0859, -0.0812, -0.0371, 0.316, -0.342, -0.0469, 0.0977, 0.084, -0.0972, 0.0518, -0.05, -0.221, 0.229, 0.126, 0.249, 0.021, -0.11, 0.0581, -0.0336, 0.13, 0.0242, 0.0348, -0.26, 0.242, -0.322, 0.0145, -0.159, -0.0837, 0.165, 0.00159, 0.31, 0.316, 0.00739, 0.241, 0.0491, -0.0986, 0.0291, 0.149, -0.0483, 0.236, 0.221, 0.125, -0.139, 0.154, 0.0719, 0.13, -0.106, 0.0601, 0.315, 0.11, 0.085, 0.0771, -0.0217, 0.0612, -0.19, 0.208, -0.163, 0.114, 0.201, 0.0607, 0.128, -0.311, -0.28, -0.156, 0.0415, 0.0988, 0.17, -0.0349, 0.208, -0.099, 0.00439, -0.0728, -0.0425, -0.409, -0.276, 0.164, -0.558, -0.202, 0.212, -0.0981, 0.231, 0.276, 0.168, -0.045, 0.172, -0.377, -0.00352, -0.302, 0.174, 0.33, 0.201, 0.118, -0.138, -0.107, 0.0862, 0.106, 0.145, 0.00305, 0.0181, 0.